name: Continuous Testing

on:
  pull_request:
    types: ["opened", "synchronize"]
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Copy WASM files
        run: pnpm run copy-wasm
      
      - name: Run tests
        run: pnpm test
      
      - name: Build project
        run: pnpm run build